[project]
name = "papaya"
version = "1.0.0-dev"
requires-python = ">= 3.14"
dependencies = [
    "click",
    "configurenv",
    "flask",
    "jq",
    "pysolr",
    "python-dotenv",
    "pyyaml",
    "requests",
    "waitress",
]

[project.scripts]
papaya = "papaya.server:run"
